server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Disable caching for HTML and JS so browser always gets the latest code.
    location ~* \.(html|js)$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
        add_header Pragma "no-cache";
        expires -1;
        try_files $uri $uri/ =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
